# Generated by Django 5.1.3 on 2024-11-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
