# Generated by Django 5.1.3 on 2024-12-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
