# Generated by Django 5.1.3 on 2024-12-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0004_cake_weight'),
        ('productsApp', '0005_order_orderitem'),
    ]

    operations = [
    ]
